name: Deploy Go

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Dependencies
        run: |
          git pull origin master
          go mod vendor

      - name: Run Build
        run: |
          go build .
          promethical

      - name: End Process
        run: echo "Started"
